### ISSUE TITLE
Add Algorand Resources

### ISSUE THREAD

**Issue by nuke-web3** [scetx/build-a-blockchain-startup#16]
- [x] To the TBA class workshop they will host
- [x] To the resources page in it's own setion

1. updated the resource kit from:
https://docs.google.com/document/d/1qB-c7zWXSQ8tS7Lk4xz_suZ248SpirAQSpJGz61wsjA/edit
pointed by
https://www.notion.so/Algorand-Foundation-cdf898fbfe79445784dbde0bd04cad7e

2. updated the homework https://github.com/algorandfoundation/buildweb3 that can be used as a "Getting started" tutorial on Algorand or as a homework like last time.

3. I've *not* yet updated the list of projects pointed by https://www.notion.so/Algorand-Foundation-cdf898fbfe79445784dbde0bd04cad7e. Some of them are not ideal anymore.

**Comment by timg512372** [comment]
Updated the resources page with all the links
