### ISSUE TITLE
ETH assignments updates

### ISSUE THREAD

**Issue by nuke-web3** [scetx/build-a-blockchain-startup#26]
Feature some of @austintgriffith 's epic work:
 
https://austingriffith.com/portfolio/ethbuild/
https://austingriffith.com/

https://www.youtube.com/playlist?list=PLJz1HruEnenCXH7KW7wBCEBnBLOVkiqIi

**Comment by nuke-web3** [comment]
3/1 date for virtual 1.5 our event with @austintgriffith - what should the following be?
- Title of talk & mini abstract
- slides to share on this site
- materials used/referenced (to add to the site resources and share before/after the event)

**Comment by austintgriffith** [comment]
🛠eth.build to 🏗scaffold-eth: building decentralized apps

it will be a live demo, no slides 

I will use eth.build and scaffold-eth: https://github.com/austintgriffith/scaffold-eth

**Comment by austintgriffith** [comment]
https://eth.build/
