### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by MelissaDsd** [scetx/build-a-blockchain-startup#27]
Links for:
📰 Self-guided Overview of Class Resources
and
📺 Watch *all* Cryptography Videos
are broken. 
Error message: "404. There isn't a GitHub Pages site here. If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account."
Screenshot attached.

<img width="1440" alt="Capture d’écran 2022-01-25 à 12 17 26" src="https://user-images.githubusercontent.com/56046464/151052935-25910375-9908-411f-b7b7-0f5bc648fc84.png">

**Comment by nuke-web3** [comment]
Thanks for the spot! this fixes the issue: https://github.com/scetx/build-a-blockchain-startup/pull/28
