### ISSUE TITLE
Update schedule with in person reqired dates

### ISSUE THREAD

**Issue by nuke-web3** [scetx/build-a-blockchain-startup#47]
New column on schedule: When Tommaso or Dan is in person, we identify this on the schedule and insist the class is there in person

Dan will be available for in person office hours with a signup form listed (a calendly to be added for virtual ones)
Signup for virtual office hours: https://calendly.com/dan-shields-berkeley/20

In person will be added an annouced closer to the times of in-person classes. Dan in-person class dates:
- April 12th, 26th, 28th
Other in person dates:
- Collider Cup May 6th (plus a day or two around them)

Final pitch date: April 28th -- need to have Tommaso update his plans for that date.

**Comment by timg512372** [comment]
#51
