### ISSUE TITLE
Add Entrepreneur classes

### ISSUE THREAD

**Issue by nuke-web3** [scetx/build-a-blockchain-startup#5]
Add Entrepreneur classes added base on info in here: https://docs.google.com/spreadsheets/d/1dcynADRl7Hrg98dVi3z_3NhSgJ0GCcOY8JavXrc0dXM/edit#gid=1709744959

This should be in the Schedule and new class pages (as needed): 
- [x] https://github.com/timg512372/dapp-course-website/blob/gh-pages/_data/schedule.yml
- [ ] https://github.com/timg512372/dapp-course-website/tree/gh-pages/_pages/class

**Comment by timg512372** [comment]
Updated the schedule page. Left the individual class page for now.
